# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Mon Nov  6 18:53:50 2017
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 180, 211, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.normal_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.normal_btn.setObjectName("normal_btn")
        self.verticalLayout_2.addWidget(self.normal_btn)
        self.eco_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.eco_btn.setObjectName("eco_btn")
        self.verticalLayout_2.addWidget(self.eco_btn)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(290, 180, 221, 248))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.crrnt_temp_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.crrnt_temp_label.setObjectName("crrnt_temp_label")
        self.verticalLayout_3.addWidget(self.crrnt_temp_label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.curent_temp_box = QtWidgets.QTextEdit(self.verticalLayoutWidget_2)
        self.curent_temp_box.setObjectName("curent_temp_box")
        self.horizontalLayout_2.addWidget(self.curent_temp_box)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.set_temp_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.set_temp_lbl.setObjectName("set_temp_lbl")
        self.verticalLayout_3.addWidget(self.set_temp_lbl)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.up_temp_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.up_temp_btn.setObjectName("up_temp_btn")
        self.verticalLayout.addWidget(self.up_temp_btn)
        self.down_temp_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.down_temp_btn.setObjectName("down_temp_btn")
        self.verticalLayout.addWidget(self.down_temp_btn)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.set_temp_box = QtWidgets.QTextEdit(self.verticalLayoutWidget_2)
        self.set_temp_box.setObjectName("set_temp_box")
        self.horizontalLayout_3.addWidget(self.set_temp_box)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(550, 180, 211, 111))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.heat_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.heat_btn.setObjectName("heat_btn")
        self.verticalLayout_4.addWidget(self.heat_btn)
        self.cool_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.cool_btn.setObjectName("cool_btn")
        self.verticalLayout_4.addWidget(self.cool_btn)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(290, 30, 221, 81))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralWidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(40, 140, 211, 37))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralWidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(290, 140, 221, 37))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.centralWidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(550, 140, 213, 37))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 0, 0, 1, 1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        MainWindow.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.normal_btn.setText(_translate("MainWindow", "Normal"))
        self.eco_btn.setText(_translate("MainWindow", "Eco"))
        self.crrnt_temp_label.setText(_translate("MainWindow", "Current:"))
        self.set_temp_lbl.setText(_translate("MainWindow", "Set:"))
        self.up_temp_btn.setText(_translate("MainWindow", "Increase"))
        self.down_temp_btn.setText(_translate("MainWindow", "Decrease"))
        self.heat_btn.setText(_translate("MainWindow", "Heat"))
        self.cool_btn.setText(_translate("MainWindow", "Cool"))
        self.label.setText(_translate("MainWindow", "EcoHub"))
        self.label_2.setText(_translate("MainWindow", "Mode"))
        self.label_3.setText(_translate("MainWindow", "Temperature"))
        self.label_4.setText(_translate("MainWindow", "Heating + Cooling"))

